### ISSUE TITLE
Failing conversion of error_on specs...

### ISSUE THREAD

**Issue by jasonm23** [yujinakayama/transpec#104] opened 2015-07-01 02:25 UTC
We originally had the following expectations: (subject is a model, with `.date` property.)

    entry.date = '2013-05-31'
    expect(entry).to_not be_valid
    expect(entry).to have(1).error_on :date

    entry.date = '2013-04-30'
    entry.valid?
    expect(entry).to have(0).errors_on :date

Which transpec updates to:

    entry.date = '2013-05-31'
    expect(entry).to_not be_valid
    expect(entry.error_on :date.size).to eq(1)

    entry.date = '2013-04-30'
    entry.valid?
    expect(entry.errors_on :date.size).to eq(0)

Which should be:

    entry.date = '2013-05-31'
    expect(entry).to_not be_valid
    expect(entry.error_on(:date).count).to eq(1)

    entry.date = '2013-04-30'
    entry.valid?
    expect(entry.errors_on(:date).count).to eq(0)

However, Since `to_have` and `errors_on` / `error_on` are provided by [rspec-collection_matchers][1].  

I thought `error_on` [wasn't supported in rspec 3.][2]

[1]:https://github.com/rspec/rspec-collection_matchers
[2]:http://stackoverflow.com/questions/24268630/how-to-convert-errors-on-to-rspec-3-syntax

**Comment by yujinakayama** [comment] 2015-07-01 12:44
Didn't you use `--skip-dynamic-analysis` option?

**Comment by jasonm23** [comment] 2015-07-01 12:58
No, this was a straight run, no options

**Comment by yujinakayama** [comment] 2016-04-12 03:06
Closing since the issue could not be reproduced in my environment. Please reopen if you can provide reproducible example.

**Closed by yujinakayama** 2016-04-12 03:06 UTC
