### ISSUE TITLE
Transpec killed, no error output

### ISSUE THREAD

**Issue by BattleBrisket** [yujinakayama/transpec#116] opened 2016-02-08 20:19 UTC
```
$ transpec
Copying the project for dynamic analysis...
Running dynamic analysis with command "bundle exec rspec"...
Killed
$
```

There's a significant pause between the `bundle exec rspec` and `Killed` outputs, so it's doing something, I just have no idea what.

- Transpec 3.2.0
- Ruby 2.2.2p95
- RSpec 2.99
- Normal green test results
- Ubuntu 14.04.3 (running via Vagrant, if that matters)

**Comment by nathanhamilton** [comment] 2016-02-09 17:20
I am having a very similar issue. I run transpec and it hangs on `Running dynamic analysis with command "bundle exec rspec"...` but doesn't return the notice `Killed`. Out of curiosity, @BattleBrisket are you running the most recent version of Transpec? You can find out by running `transpec --version` and the version should be `3.2.0` if it is the latest.

I am running Ruby 2.2.3, RSpec 2.99, OSX 10.11.3 (El Capitan) and have a green test suite.

**Comment by jeremykay** [comment] 2016-02-09 19:08
I'm having a similar issue, transpec hangs with:
```
Copying the project for dynamic analysis...
Running dynamic analysis with command "bundle exec rspec"...
```

If I run individual specs to transcode it works, but just seems to hang at this point if attempting the entire spec suite (our spec suite isn't that large).

ruby-2.1.4, transpec 3.2.0, RSpec 2.99, OSX 10.11.3 (El Capitan),

**Comment by BattleBrisket** [comment] 2016-02-10 22:30
Updated original post with more environment details (per @nathanhamilton, plus further consideration)

**Comment by yujinakayama** [comment] 2016-02-16 04:29
It's caused by the new version of `parser` gem dependency and should have been fixed in Transpec 2.3.1.

**Comment by BattleBrisket** [comment] 2016-02-16 14:03
> fixed in Transpec 2.3.1.

You mean _3.2.1_, correct?

**Comment by nathanhamilton** [comment] 2016-02-16 15:26
Thanks @yujinakayama. Updated the Transpec gem and everything is working well now!

**Comment by yujinakayama** [comment] 2016-02-17 04:17
> You mean _3.2.1_, correct?

:ok_woman:

**Closed by yujinakayama** 2016-02-17 04:17 UTC

**Comment by BattleBrisket** [comment] 2016-02-17 14:23
Hey don't shoot the messenger. This is an open source project, and I think we've all seen dumber versioning schemes.
