### ISSUE TITLE
NoMethodError: undefined method `this' for #<Gem::Specification:0x1ff2 transpec-3.2.2>

### ISSUE THREAD

**Issue by dennis-d** [yujinakayama/transpec#119] opened 2016-03-30 03:53 UTC
JRuby 1.7.24

When running transpec command in rails folder I get this exception, mri version seems to be fine. 

NoMethodError: undefined method `this' for #<Gem::Specification:0x1ff2 transpec-3.2.2>
            method_missing at org/jruby/RubyBasicObject.java:1555
            method_missing at /Users/dennis/.rvm/rubies/jruby-1.7.24/lib/ruby/shared/rubygems/specification.rb:2162
  find_active_stub_by_path at /Users/dennis/.rvm/rubies/jruby-1.7.24/lib/ruby/shared/rubygems/specification.rb:1057
                   require at /Users/dennis/.rvm/rubies/jruby-1.7.24/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:64
                    (root) at /Users/dennis/.rvm/gems/jruby-1.7.24/gems/transpec-3.2.2/bin/transpec:5
                      load at org/jruby/RubyKernel.java:1059
                    (root) at /Users/dennis/.rvm/gems/jruby-1.7.24/bin/transpec:1
                      eval at org/jruby/RubyKernel.java:1079
                    (root) at /Users/dennis/.rvm/gems/jruby-1.7.24/bin/jruby_executable_hooks:15

**Comment by yujinakayama** [comment] 2016-03-30 03:55
Seems to be duplicate of #114.

**Closed by yujinakayama** 2016-03-30 03:55 UTC
